{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "FDPUgYC4xY3j"
      },
      "outputs": [],
      "source": [
        "streamlit\n",
        "pandas\n",
        "matplotlib\n",
        "requests"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import streamlit as st\n",
        "import requests\n",
        "import pandas as pd\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "API = \"https://8000-m-s-30qtpp4kk02pl-d.us-east1-1.prod.colab.dev\"\n",
        "\n",
        "st.set_page_config(page_title=\"Restaurant Dashboard\", layout=\"wide\")\n",
        "st.title(\"Restaurant Daily Performance\")\n",
        "\n",
        "@st.cache_data\n",
        "def get_metrics():\n",
        "    try:\n",
        "        r = requests.get(f\"{API}/metrics/daily\", timeout=10)\n",
        "        df = pd.DataFrame(r.json())\n",
        "        if not df.empty:\n",
        "            for col in [\"total_sales\", \"labor_expenses\", \"food_expenses\", \"other_expenses\", \"profit\"]:\n",
        "                df[col] = pd.to_numeric(df[col], errors=\"coerce\").fillna(0.0)\n",
        "        return df\n",
        "    except Exception as e:\n",
        "        st.warning(f\"Could not fetch metrics: {e}\")\n",
        "        return pd.DataFrame()\n",
        "\n",
        "df = get_metrics()\n",
        "\n",
        "st.subheader(\"Today's KPIs\")\n",
        "\n",
        "if not df.empty:\n",
        "    latest = df.iloc[-1]\n",
        "    col1, col2, col3, col4, col5 = st.columns(5)\n",
        "\n",
        "    col1.metric(\"Sales\", f\"${latest['total_sales']:.2f}\")\n",
        "    col2.metric(\"Labor\", f\"${latest['labor_expenses']:.2f}\")\n",
        "    col3.metric(\"Food\", f\"${latest['food_expenses']:.2f}\")\n",
        "    col4.metric(\"Other\", f\"${latest['other_expenses']:.2f}\")\n",
        "    col5.metric(\"Profit\", f\"${latest['profit']:.2f}\")\n",
        "else:\n",
        "    st.info(\"No data yet. Add today's metrics below.\")\n",
        "\n",
        "st.subheader(\"Daily Trends\")\n",
        "\n",
        "if not df.empty:\n",
        "    df[\"date\"] = pd.to_datetime(df[\"date\"])\n",
        "\n",
        "    fig, ax = plt.subplots(figsize=(10, 4))\n",
        "    ax.plot(df[\"date\"], df[\"total_sales\"], label=\"Sales\")\n",
        "    ax.plot(df[\"date\"], df[\"labor_expenses\"], label=\"Labor\")\n",
        "    ax.plot(df[\"date\"], df[\"food_expenses\"], label=\"Food\")\n",
        "    ax.plot(df[\"date\"], df[\"other_expenses\"], label=\"Other\")\n",
        "    ax.plot(df[\"date\"], df[\"profit\"], label=\"Profit\", linewidth=3)\n",
        "    ax.legend()\n",
        "    ax.set_xlabel(\"Date\")\n",
        "    ax.set_ylabel(\"Amount ($)\")\n",
        "    fig.autofmt_xdate()\n",
        "    st.pyplot(fig)\n",
        "else:\n",
        "    st.write(\"No data to plot yet.\")\n",
        "\n",
        "st.subheader(\"Add Daily Metrics\")\n",
        "\n",
        "with st.form(\"daily_form\"):\n",
        "    date = st.date_input(\"Date\")\n",
        "    sales = st.number_input(\"Total Sales\", min_value=0.0, step=10.0)\n",
        "    labor = st.number_input(\"Labor Expenses\", min_value=0.0, step=10.0)\n",
        "    food = st.number_input(\"Food Expenses\", min_value=0.0, step=10.0)\n",
        "    other = st.number_input(\"Other Expenses\", min_value=0.0, step=10.0)\n",
        "\n",
        "    submitted = st.form_submit_button(\"Submit\")\n",
        "\n",
        "    if submitted:\n",
        "        payload = {\n",
        "            \"date\": str(date),\n",
        "            \"total_sales\": float(sales),\n",
        "            \"labor_expenses\": float(labor),\n",
        "            \"food_expenses\": float(food),\n",
        "            \"other_expenses\": float(other)\n",
        "        }\n",
        "        try:\n",
        "            resp = requests.post(f\"{API}/log/daily\", json=payload, timeout=10)\n",
        "            if resp.status_code == 200:\n",
        "                st.success(\"Daily metrics added!\")\n",
        "                st.cache_data.clear()\n",
        "            else:\n",
        "                st.error(f\"Error from API: {resp.status_code} {resp.text}\")\n",
        "        except Exception as e:\n",
        "            st.error(f\"Could not reach backend: {e}\")\n",
        "\n",
        "st.subheader(\"History\")\n",
        "\n",
        "if not df.empty:\n",
        "    st.dataframe(df.sort_values(\"date\", ascending=False))\n",
        "else:\n",
        "    st.write(\"No historical data yet.\")"
      ],
      "metadata": {
        "id": "KodesooGvrMp"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}
